# Generated by Django 5.0.7 on 2024-07-17 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="updated_at",
        ),
    ]
