# Generated by Django 5.0.7 on 2024-07-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_blog_created_at_remove_blog_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="user_type",
            field=models.CharField(
                choices=[("Dr", "Doctor"), ("Pt", "Patient")],
                default="Dr",
                max_length=2,
            ),
        ),
    ]
