# Generated by Django 5.0.7 on 2024-07-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0004_remove_blog_user_type_blog_cataegory_blog_is_draft_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="cataegory",
            field=models.CharField(
                choices=[
                    ("immunization", "Immunization"),
                    ("mental_health", "Mental health"),
                    ("covid_19", "Covid 19"),
                    ("heart_disease", "Heart disease"),
                ],
                default="Immunization",
                max_length=13,
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="photo",
            field=models.ImageField(blank=True, upload_to="photos/"),
        ),
    ]
