# Generated by Django 5.0.7 on 2024-07-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_appointment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="appointed_doctor",
            new_name="patient",
        ),
        migrations.AddField(
            model_name="appointment",
            name="doctor_appointed",
            field=models.CharField(default="Faizan", max_length=30),
            preserve_default=False,
        ),
    ]
