# Generated by Django 5.0.7 on 2024-07-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_rename_appointed_doctor_appointment_patient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="add_event",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
